services:
  suprim-gateway:
    container_name: kijaro
    image: suprim/kijaro:${COMMIT_HASH}
    build: .
    ports:
      - "${WEB_PORT:-127.0.0.1:3001}:8080"
    volumes:
      - ./data:/app/packages/data
      - ${KIRO_CREDS_HOST_PATH}:/app/creds:ro
    env_file:
      - .env
    restart: unless-stopped
